name: CI_Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci
        working-directory: project

      - name: test in container
        run: docker build -t node-docker-image-test --no-cache --target test .

      - name: Build Application
        run: npm run build
        working-directory: project
